added folder recursion to ingest.py
PromtEngineer/localGPT pull request #369
Opened 2023-08-15 10:58 UTC by ChrisAylen

I have added file recursion to ingest.py

2023-08-18 20:17 UTC, creuzerm commented
I was just thinking about this for an idea. Looking this without trying it, the Sources that get output in the end still gives us just the file name and not the path and filename, right?

2023-08-19 12:53 UTC, ChrisAylen commented
Yes, the way the code is currently structured, only the filename is considered in the 'load_documents' function without including the complete path.
________________________________
From: Mike Creuzer ***@***.***>
Sent: Friday, August 18, 2023 9:17:25 PM
To: PromtEngineer/localGPT ***@***.***>
Cc: Chris Aylen ***@***.***>; Author ***@***.***>
Subject: Re: [PromtEngineer/localGPT] added folder recursion to ingest.py (PR #369)


I was just thinking about this for an idea. Looking this without trying it, the Sources that get output in the end still gives us just the file name and not the path and filename, right?

—
Reply to this email directly, view it on GitHub<https://github.com/PromtEngineer/localGPT/pull/369#issuecomment-1684393459>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AFNRJNG237KKCO26TR3TOADXV7EVLANCNFSM6AAAAAA3Q5G37M>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-08-20 16:58 UTC, hedgar2017 requested changes

2023-08-20 16:58 UTC, hedgar2017 commented on ingest.py
> +    for root, _, files in os.walk(source_dir):
`pathlib.Path(source_dir).glob("**/*")` is less verbose.

2023-08-29 05:40 UTC, merged